<?php
/***CONFIGURATOR***/
$sugar_config['enable_action_menu'] = true;
$sugar_config['email_xss'] = 'YToxOntzOjY6InNjcmlwdCI7czo2OiJzY3JpcHQiO30=';
$sugar_config['default_theme'] = 'ModernAqua';
$sugar_config['disabled_themes'] = '';
$sugar_config['passwordsetting']['SystemGeneratedPasswordON'] = '0';
$sugar_config['passwordsetting']['generatepasswordtmpl'] = '72d2b8dd-dd34-8e92-d235-509ab7eb7c63';
$sugar_config['passwordsetting']['lostpasswordtmpl'] = '72d2b8dd-dd34-8e92-d235-509ab7eb7c63';
$sugar_config['passwordsetting']['systexpiration'] = '1';
$sugar_config['passwordsetting']['systexpirationtime'] = '1';
$sugar_config['passwordsetting']['systexpirationtype'] = '7';
$sugar_config['SAML_loginurl'] = '';
$sugar_config['SAML_X509Cert'] = '';
$sugar_config['authenticationClass'] = '';
$sugar_config['default_currency_iso4217'] = 'RUB';
$sugar_config['default_currency_name'] = 'RUB';
$sugar_config['developerMode'] = false;
$sugar_config['logger']['level'] = 'error';
$sugar_config['logger']['file']['maxSize'] = '10MB';
$sugar_config['asterisk_host'] = '194.125.236.103';
$sugar_config['asterisk_port'] = '5038';
$sugar_config['asterisk_user'] = 'admin';
$sugar_config['asterisk_secret'] = 'Mak1Mozer0';
$sugar_config['asterisk_soapuser'] = 'olga';
$sugar_config['asterisk_soappass'] = 'kaset45783592698';
$sugar_config['asterisk_context'] = 'from-internal';
$sugar_config['asterisk_expr'] = '^(sip\\/[1-9][0-9][0-9]?[0-9]?-|Local)';
$sugar_config['asterisk_dialout_channel'] = 'SIP/###';
$sugar_config['asterisk_dialin_ext_match'] = 'Local\\/(?:.*?)(\\d\\d\\d?\\d?\\d?)@';
$sugar_config['asterisk_rg_detect_expr'] = '^Local\\/RG';
$sugar_config['asterisk_rg_cell_ring_expr'] = '^Local\\/\\d{7,10}';
$sugar_config['asterisk_call_subject_inbound_abbr'] = 'Вх: ';
$sugar_config['asterisk_call_subject_outbound_abbr'] = 'Исх: ';
$sugar_config['asterisk_call_subject_max_length'] = '50';
$sugar_config['asterisk_listener_poll_rate'] = '5000';
$sugar_config['asterisk_opencnam_retries'] = '4';
$sugar_config['asterisk_short_call_status'] = 'Held';
$sugar_config['asterisk_hide_call_popups_after_mins'] = '60';
$sugar_config['default_language'] = 'ru_ru';
$sugar_config['default_date_format'] = 'd/m/Y';
$sugar_config['disabled_languages'] = '';
$sugar_config['email_default_delete_attachments'] = false;
/***CONFIGURATOR***/